version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.3.7"

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - "echo Build started on `date`"
      - "aws sts get-caller-identity"