version: 0.2
env:
  shell: bash
  variables:
    TF_VERSION: "1.3.7"
    JF_PIP_FILE: "test.txt"
  # parameter-store:
  #   JF_PYRC_FILE: '/secure/aue1/${ENVIRONMENT_DEVOPS}/codebuild/bright_pypi_pypirc'
  #   JF_PIP_FILE: '/secure/aue1/${ENVIRONMENT_DEVOPS}/codebuild/bright_pypi_pipconf'

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Install dependencies"
      - python --version
      - pip install -r tests/glue_requirements.txt
     
  build:
    commands:
      - "echo Build started on `date`"
      - "echo $PWD"
      - "ls"
      - "aws sts get-caller-identity"
      - "pytest tests/test/test_glue.py"
      #- cd containers/tests
      #- docker build -t tests --build-arg JF_PIP_FILE="${JF_PIP_FILE}" .
      #- docker run -e DISABLE_SSL=true -v $PWD:/home/glue_user/workspace/ --rm tests:latest -c "pytest tests/test/test_glue.py"

