aws_shared_credential_file_path  = "~/.aws/credentials"
aws_profile_code                 = "devops"
aws_profile_dev                  = "test"
zone                             = "z1"
environment_devops               = "c1"
environment_dev                  = "t1"
code_source_branch               = "test"
enable_codepipeline_notification = true
sns_notification_create_approval = false
#sns_arn_codepipeline_notification= "arn:aws:sns:us-east-2:036360966563:datapipeline_cicd_oidh-approval"